### ISSUE TITLE
It is mute even though player/waveform is working

### ISSUE THREAD

**Issue by Inambe** [katspaugh/wavesurfer-multitrack#1]
I'm not sure what is the issue but when I play a multi-track, no voice comes out of the speakers. I've used wavesurfer.js on the same site and that works fine. It's just `wavesurfer-multitrack` issue.

**Comment by katspaugh** [comment]
Please paste your code on StackBlitz/CodeSandbox/CodePen.

**Comment by katspaugh** [comment]
Please feel free to reopen this issue if you manage to make a reproducible example.

**Comment by v1ada** [comment]
I encountered the same problem, using the example from the official website
This my code: https://codepen.io/v1ada/pen/wvQqLvZ

**Comment by katspaugh** [comment]
So it's the same code as on the website? The only difference is that the audio URLs are from localhost? Which obviously won't work.
Does it work for you on https://wavesurfer-js.org/examples/#multitrack.js?

**Comment by v1ada** [comment]
Thank you for your answer, I have now found the problem.
I use online links and cross-domain problems occur: 
MediaElementAudioSource outputs zeroes due to CORS access restrictions for url.
I need to add  `crossorigin="anonymous"` attribute in audio
 has an option to achieve this? Or is there detailed documentation about this plugin?

**Comment by v1ada** [comment]
> 那么这个代码和网站上的代码是一样的吗？唯一的区别是音频 URL 来自本地主机？这显然行不通。 它对您有用吗https://wavesurfer-js.org/examples/#multitrack.js？

Thank you for your answer, I have now found the problem.
I use online links and cross-domain problems occur:
MediaElementAudioSource outputs zeroes due to CORS access restrictions for url.
I need to add crossorigin="anonymous" attribute in audio
has an option to achieve this? Or is there detailed documentation about this plugin?

**Comment by v1ada** [comment]
> So it's the same code as on the website? The only difference is that the audio URLs are from localhost? Which obviously won't work. Does it work for you on https://wavesurfer-js.org/examples/#multitrack.js?

Thank you for your answer, I have now found the problem.
I use online links and cross-domain problems occur:
MediaElementAudioSource outputs zeroes due to CORS access restrictions for url.
I need to add crossorigin="anonymous" attribute in audio
has an option to achieve this? And is there detailed documentation about this plugin?

**Comment by v1ada** [comment]
> So it's the same code as on the website? The only difference is that the audio URLs are from localhost? Which obviously won't work. Does it work for you on https://wavesurfer-js.org/examples/#multitrack.js?

Thank you for your answer, I have now found the problem.
I use online links and cross-domain problems occur:
MediaElementAudioSource outputs zeroes due to CORS access restrictions for url.
I need to add crossorigin="anonymous" attribute in audio
has an option to achieve this? And is there detailed documentation about this plugin?

**Comment by katspaugh** [comment]
You can add it here and make a PR: https://github.com/katspaugh/wavesurfer-multitrack/blob/e60fcbd7cb2fdacc3bccb5b4bfa55af008e2fa5c/src/multitrack.ts#L130

There are no docs yet unfortunately.

**Comment by v1ada** [comment]
> You can add it here and make a PR:
> 
> https://github.com/katspaugh/wavesurfer-multitrack/blob/e60fcbd7cb2fdacc3bccb5b4bfa55af008e2fa5c/src/multitrack.ts#L130
> 
> There are no docs yet unfortunately.

Thank you for your answer

**Comment by Inambe** [comment]
Made a PR #10 to fix it.
